language: php

matrix:
  include:
    - php: 7.2
      env: QA=yes
    - php: 7.3
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer selfupdate
  - composer install
  - |
    if [ "$QA" == "yes" ]; then
      composer global require 'codeclimate/php-test-reporter:*' 'satooshi/php-coveralls:*' sugared-rim/cs:^2.1
      export PATH=$PATH:`composer global config bin-dir --absolute`
    fi

script:
  - composer travis
  - if [ "$QA" == "yes" ]; then composer lint; fi

after_success:
  - |
    if [ "$QA" == "yes" ]; then
      travis_retry test-reporter
      travis_retry coveralls -v
    fi
